CREATE DATABASE IF NOT EXISTS vnlibrary CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE vnlibrary;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS password_resets, sessions, notifications, audit_logs, payments, purchases, fines, reservations, borrow_items, borrows, books, categories, readers, users, settings;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,username VARCHAR(80) NOT NULL UNIQUE,email VARCHAR(160),password_hash VARCHAR(255) NOT NULL,
 role ENUM('ADMIN','LIBRARIAN') NOT NULL DEFAULT 'LIBRARIAN',active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_users_name(name)
) ENGINE=InnoDB;
CREATE TABLE categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL UNIQUE,description VARCHAR(500)) ENGINE=InnoDB;
CREATE TABLE books(
 id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,author VARCHAR(160) NOT NULL,publisher VARCHAR(160),publish_year INT,isbn VARCHAR(40),
 quantity INT NOT NULL DEFAULT 1,available INT NOT NULL DEFAULT 1,price DECIMAL(15,2) NOT NULL DEFAULT 0,shelf VARCHAR(80),category_id INT NULL,description TEXT,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL,INDEX idx_books_title(title),INDEX idx_books_author(author),INDEX idx_books_category(category_id)
) ENGINE=InnoDB;
CREATE TABLE readers(
 id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,email VARCHAR(160),phone VARCHAR(40),address VARCHAR(255),card_number VARCHAR(60) NOT NULL UNIQUE,birth_date DATE NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_readers_name(name),INDEX idx_readers_phone(phone)
) ENGINE=InnoDB;
CREATE TABLE borrows(
 id INT AUTO_INCREMENT PRIMARY KEY,reader_id INT NOT NULL,borrow_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,due_date DATETIME NOT NULL,return_date DATETIME NULL,
 status ENUM('BORROWING','OVERDUE','RETURNED') NOT NULL DEFAULT 'BORROWING',note VARCHAR(500),created_by INT NULL,
 FOREIGN KEY(reader_id) REFERENCES readers(id),FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_borrows_status(status),INDEX idx_borrows_due(due_date)
) ENGINE=InnoDB;
CREATE TABLE borrow_items(id INT AUTO_INCREMENT PRIMARY KEY,borrow_id INT NOT NULL,book_id INT NOT NULL,quantity INT NOT NULL DEFAULT 1,FOREIGN KEY(borrow_id) REFERENCES borrows(id) ON DELETE CASCADE,FOREIGN KEY(book_id) REFERENCES books(id),UNIQUE KEY uq_borrow_book(borrow_id,book_id)) ENGINE=InnoDB;
CREATE TABLE reservations(
 id INT AUTO_INCREMENT PRIMARY KEY,reader_id INT NOT NULL,book_id INT NOT NULL,reserved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at DATETIME NULL,
 status ENUM('WAITING','READY','BORROWED','CANCELLED','EXPIRED') NOT NULL DEFAULT 'WAITING',note VARCHAR(500),FOREIGN KEY(reader_id) REFERENCES readers(id),FOREIGN KEY(book_id) REFERENCES books(id),INDEX idx_res_status(status)
) ENGINE=InnoDB;
CREATE TABLE fines(
 id INT AUTO_INCREMENT PRIMARY KEY,reader_id INT NOT NULL,borrow_id INT NULL,amount DECIMAL(15,2) NOT NULL,reason VARCHAR(255) NOT NULL,status ENUM('UNPAID','PAID') NOT NULL DEFAULT 'UNPAID',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,paid_at DATETIME NULL,
 FOREIGN KEY(reader_id) REFERENCES readers(id),FOREIGN KEY(borrow_id) REFERENCES borrows(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE purchases(
 id INT AUTO_INCREMENT PRIMARY KEY,supplier VARCHAR(180) NOT NULL,book_id INT NOT NULL,quantity INT NOT NULL,unit_price DECIMAL(15,2) NOT NULL,total_amount DECIMAL(15,2) NOT NULL,
 status ENUM('PENDING','PAID') NOT NULL DEFAULT 'PENDING',method ENUM('CASH','BANK_TRANSFER','CARD') NULL,note VARCHAR(500),purchase_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,paid_at DATETIME NULL,created_by INT NULL,
 FOREIGN KEY(book_id) REFERENCES books(id),FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_purchase_status(status)
) ENGINE=InnoDB;
CREATE TABLE payments(id INT AUTO_INCREMENT PRIMARY KEY,purchase_id INT NOT NULL,amount DECIMAL(15,2) NOT NULL,method ENUM('CASH','BANK_TRANSFER','CARD') NOT NULL,note VARCHAR(500),paid_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by INT NULL,FOREIGN KEY(purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE notifications(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,title VARCHAR(200) NOT NULL,message TEXT NOT NULL,read_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_notif_user(user_id,read_at)) ENGINE=InnoDB;
CREATE TABLE audit_logs(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,action VARCHAR(80) NOT NULL,entity VARCHAR(80) NOT NULL,entity_id INT NULL,details TEXT,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,INDEX idx_audit_time(created_at)) ENGINE=InnoDB;
CREATE TABLE sessions(id VARCHAR(80) PRIMARY KEY,user_id INT NOT NULL,expires_at DATETIME NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_session_exp(expires_at)) ENGINE=InnoDB;
CREATE TABLE password_resets(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,token VARCHAR(120) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,used_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE settings(`key` VARCHAR(80) PRIMARY KEY,`value` VARCHAR(500) NOT NULL);
