import mysql from 'mysql2/promise';import dotenv from 'dotenv';import crypto from 'crypto';dotenv.config();
const c=await mysql.createConnection({host:process.env.DB_HOST||'127.0.0.1',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'vnlibrary'});
const hash=p=>crypto.scryptSync(p,'VNLibrary_SALT_2026',64).toString('hex');
const q=(sql,p=[])=>c.execute(sql,p);
const categories=[['Văn học','Tiểu thuyết, truyện và tác phẩm văn học'],['Khoa học','Khoa học tự nhiên và khám phá'],['Công nghệ','Công nghệ thông tin và kỹ thuật'],['Kinh tế','Kinh doanh, quản trị và tài chính'],['Lịch sử','Lịch sử Việt Nam và thế giới'],['Tâm lý','Tâm lý học và phát triển bản thân'],['Thiếu nhi','Sách dành cho thiếu nhi'],['Ngoại ngữ','Học và sử dụng ngoại ngữ'],['Giáo dục','Giảng dạy và học tập'],['Nghệ thuật','Mỹ thuật, âm nhạc và nhiếp ảnh'],['Kỹ năng sống','Kỹ năng cá nhân và nghề nghiệp'],['Du lịch','Địa lý, văn hóa và du lịch']];
for(const [n,d] of categories)await q('INSERT INTO categories(name,description) VALUES(?,?)',[n,d]);
await q('INSERT INTO users(name,username,email,password_hash,role) VALUES(?,?,?,?,?)',['Quản trị viên VNLibrary','admin','admin@vnlibrary.local',hash('admin123'),'ADMIN']);
await q('INSERT INTO users(name,username,email,password_hash,role) VALUES(?,?,?,?,?)',['Thủ thư VNLibrary','thuthu','thuthu@vnlibrary.local',hash('thuthu123'),'LIBRARIAN']);
const settings=[['libraryName','VNLibrary'],['loanDays','14'],['finePerDay','5000'],['maxBooks','5']];for(const s of settings)await q('INSERT INTO settings(`key`,`value`) VALUES(?,?)',s);
const last=['Nguyễn','Trần','Lê','Phạm','Hoàng','Võ','Đặng','Bùi','Đỗ','Ngô','Dương','Huỳnh','Phan','Mai','Đinh','Lý','Vũ','Cao','Tạ','Hồ'];
const mid=['Văn','Thị','Minh','Quang','Thanh','Ngọc','Gia','Anh','Hữu','Thu','Phương','Đức','Hoài','Kim','Bảo','Khánh'];
const first=['An','Bình','Châu','Dũng','Hà','Hạnh','Hải','Hiền','Hùng','Khang','Lan','Linh','Long','Mai','Nam','Nga','Ngân','Nhi','Phong','Quân','Quỳnh','Sơn','Tâm','Thảo','Thành','Trang','Trung','Tuấn','Vy','Yến'];
const names=[];for(const l of last)for(const m of mid)for(const f of first){if(names.length>=287)break;names.push(`${l} ${m} ${f}`)}
const titles1=['Hành Trình','Bí Mật','Dòng Sông','Ánh Sáng','Mùa Hạ','Ngọn Gió','Khu Vườn','Thành Phố','Con Đường','Khoảnh Khắc','Miền Ký Ức','Bản Nhạc','Cánh Cửa','Ngôi Nhà','Chân Trời','Vùng Đất','Những Ngày','Giấc Mơ','Lời Hứa','Cuốn Sổ','Tư Duy','Khám Phá','Năng Lượng','Thế Giới','Kỹ Thuật','Kỷ Nguyên','Nghệ Thuật','Chiến Lược','Thực Hành','Bản Đồ','Học Tập','Sức Mạnh','Kỹ Năng','Tương Lai'];
const titles2=['Mới','Xanh','Xa','Bình Yên','Kỳ Diệu','Thầm Lặng','Rực Rỡ','Bền Vững','Thông Minh','Hiện Đại','Sâu Sắc','Tự Do','Cân Bằng','Sáng Tạo','Chuyển Động','Mở Rộng','Đầu Tiên','Đích Đến','Mạch Nguồn','Cảm Hứng','Cơ Bản','Nâng Cao','Toàn Diện','Thực Tiễn','Đổi Thay','Kết Nối','Phát Triển','Bứt Phá','Khác Biệt','Đơn Giản','Chuyên Sâu','Gần Gũi','Vững Chắc','Tích Cực','Chủ Động','Tinh Gọn','Hiệu Quả'];
const authors=['Nguyễn Minh An','Trần Quốc Bảo','Lê Hoàng Anh','Phạm Thanh Hà','Võ Ngọc Lan','Đặng Minh Quân','Bùi Đức Long','Đỗ Thu Trang','Ngô Gia Huy','Dương Khánh Linh','Huỳnh Hải Nam','Phan Anh Tuấn','Mai Thảo Vy','Đinh Quang Minh','Lý Hoàng Sơn','Vũ Thành Công','Cao Nhật Hạ','Tạ Minh Châu'];
const pubs=['Nhà xuất bản Trẻ','Nhà xuất bản Kim Đồng','Nhà xuất bản Giáo dục','Nhà xuất bản Lao Động','Nhà xuất bản Tổng Hợp'];
const shelves=['A-01','A-02','B-01','B-02','C-01','C-02','D-01','D-02','E-01','E-02'];
const bookRows=[];for(let i=0;i<1213;i++){const title=`${titles1[i%titles1.length]} ${titles2[Math.floor(i/titles1.length)%titles2.length]} ${['Việt Nam','Thế Giới','Thực Tiễn','Hiện Đại','Cơ Bản','Chuyên Khảo'][Math.floor(i/(titles1.length*titles2.length))%6]}`;const qty=1+(i*7)%8;bookRows.push([title,authors[i%authors.length],pubs[i%pubs.length],2000+(i%27),`978-${String(100000000+i).padStart(9,'0')}`,qty,qty,20000+(i%80)*5000,shelves[i%shelves.length],(i%12)+1,'Tài liệu tham khảo của VNLibrary']);}
for(let i=0;i<bookRows.length;i+=200){const chunk=bookRows.slice(i,i+200);const vals=chunk.flat();const ph=chunk.map(()=>'(?,?,?,?,?,?,?,?,?,?,?)').join(',');await q(`INSERT INTO books(title,author,publisher,publish_year,isbn,quantity,available,price,shelf,category_id,description) VALUES ${ph}`,vals)}
const readerRows=names.map((n,i)=>[n,`docgia${i+1}@vnlibrary.local`,`09${String(10000000+i).slice(0,8)}`,`Khu phố ${['A','B','C','D'][i%4]}, Đà Nẵng`,`DG${String(i+1).padStart(4,'0')}`,`${1985+(i%25)}-${String((i%12)+1).padStart(2,'0')}-${String((i%27)+1).padStart(2,'0')}`]);
for(let i=0;i<readerRows.length;i+=100){const chunk=readerRows.slice(i,i+100);await q(`INSERT INTO readers(name,email,phone,address,card_number,birth_date) VALUES ${chunk.map(()=>'(?,?,?,?,?,?)').join(',')}`,chunk.flat())}
const admin=(await q("SELECT id FROM users WHERE username='admin'"))[0][0].id;
for(let i=0;i<119;i++){const readerId=(i%287)+1,bookId=i+1;const overdue=i<21;const due=overdue?`DATE_SUB(NOW(),INTERVAL ${i+2} DAY)`:`DATE_ADD(NOW(),INTERVAL ${7+(i%8)} DAY)`;const [r]=await q(`INSERT INTO borrows(reader_id,due_date,status,created_by) VALUES(?,?,?,?)`,[readerId,new Date(Date.now()+(overdue?-(i+2):7+(i%8))*86400000),overdue?'OVERDUE':'BORROWING',admin]);await q('INSERT INTO borrow_items(borrow_id,book_id,quantity) VALUES(?,?,1)',[r.insertId,bookId]);await q('UPDATE books SET available=available-1 WHERE id=?',[bookId]);if(overdue)await q('INSERT INTO fines(reader_id,borrow_id,amount,reason) VALUES(?,?,?,?)',[readerId,r.insertId,(i+2)*5000,`Quá hạn ${i+2} ngày`])}
for(let i=0;i<50;i++){const readerId=((i+30)%287)+1,bookId=((i+200)%1213)+1;const daysAgo=(i%30)+20;const [r]=await q(`INSERT INTO borrows(reader_id,due_date,return_date,status,created_by) VALUES(?,?,?,'RETURNED',?)`,[readerId,new Date(Date.now()-((i%30)+40)*86400000),new Date(Date.now()-daysAgo*86400000),admin]);await q('INSERT INTO borrow_items(borrow_id,book_id,quantity) VALUES(?,?,1)',[r.insertId,bookId])}
for(let i=0;i<30;i++){const bookId=(i%1213)+1;const qty=2+(i%5);await q('INSERT INTO purchases(supplier,book_id,quantity,unit_price,total_amount,status,note,created_by) VALUES(?,?,?,?,?,?,?,?)',[['Công ty Sách Việt','Nhà sách Thành Công','Phân phối Tri Thức','Kho Sách Miền Trung'][i%4],bookId,qty,30000+(i%8)*10000,qty*(30000+(i%8)*10000),i<12?'PAID':'PENDING','Phiếu nhập mẫu',admin]);}
for(let i=0;i<12;i++){const purchaseId=i+1;const p=(await q('SELECT total_amount FROM purchases WHERE id=?',[purchaseId]))[0][0];await q('INSERT INTO payments(purchase_id,amount,method,note,created_by) VALUES(?,?,?,?,?)',[purchaseId,p.total_amount,['CASH','BANK_TRANSFER','CARD'][i%3],'Thanh toán mẫu',admin]);await q("UPDATE purchases SET status='PAID',method=?,paid_at=NOW() WHERE id=?",[['CASH','BANK_TRANSFER','CARD'][i%3],purchaseId])}
for(let i=0;i<20;i++)await q('INSERT INTO reservations(reader_id,book_id,expires_at,status,note) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 7 DAY),?,?)',[(i%287)+1,((i+500)%1213)+1,i<15?'WAITING':'READY','Đặt sách mẫu']);
for(let i=0;i<8;i++)await q('INSERT INTO notifications(user_id,title,message) VALUES(?,?,?)',[admin,['Chào mừng','Tồn kho cần kiểm tra','Có phiếu mua chờ thanh toán','Báo cáo thư viện'][i%4],['Chào mừng bạn đến với VNLibrary.','Một số đầu sách sắp hết bản có sẵn.','Có phiếu mua sách đang chờ thanh toán.','Bạn có thể tải báo cáo CSV từ mục Báo cáo.'][i%4]]);
await q('INSERT INTO audit_logs(user_id,action,entity,details) VALUES(?,?,?,?)',[admin,'SEED','SYSTEM','Tạo dữ liệu mẫu VNLibrary']);
await c.end();console.log('Seed complete: 1213 books, 287 readers, 119 active loans, 21 overdue, purchases, payments, reservations and fines.');
